### ISSUE TITLE
CAS6: Expanding the configuration of the connection to be used to the LDAP

### ISSUE THREAD

**Issue by CloudFlo2312** [cloudogu/cas#103]
In CAS4 it has so far been possible to configure the type of connection to LDAP. In the etcd key /config/cas/ldap/use_user_connection_to_fetch_attributes it was possible to specify whether the system connection (value is false) or the user connection (value is true) should be used.

In CAS 6, or more specifically in the Ldaptive2 used there, no concrete, individual connection is now transferred, but a connection pool. Ldaptive itself decides which connection from this connection pool is to be used. Previously, a concrete connection and not a connection pool was passed to the corresponding methods. Therefore, the configuration option via the use of the system connection is now to be expanded.

Specifically, both types of connection - i.e. both the user connection and the system connection - are now used.

**Comment by ppxl** [comment]
This issue was resolved by PR #105
