### ISSUE TITLE
Implement configurable session timeouts

### ISSUE THREAD

**Issue by cwolfes** [cloudogu/cas#44]
Implement etcdkeys to configure the following `cas.properties` values:

- `tgt.maxTimeToLiveInSeconds`  (max session timeout regardless of usage)
- `tgt.timeToKillInSeconds` (session timeout without usage / no requests)

Due to our etcdkey policy we decided to implement them as

- `session_tgt/max_time_to_live_in_seconds`
- `session_tgt/time_to_kill_in_seconds`

**Comment by sklein94** [comment]
Closed with #45
