### ISSUE TITLE
the password forgot text is not applied correctly

### ISSUE THREAD

**Issue by sklein94** [cloudogu/cas#60]
The `screen.password.forgotText`-key has a higher priority in the `*de.properties` then in the default `messages.properties`. Which results in the behaviour that the `screen.password.forgotText` key, which is applied from an etcd key in the `messages.properties` is never applied. It should be removed in the `*de.properties`-files.

**Comment by Subaro** [comment]
The current implementation produces about 50 log entries each second because of the `screen.password.forgotText` is missing for the german translation file.
